### ISSUE TITLE
cache - [vite] Error when evaluating SSR module

### ISSUE THREAD

**Issue by JosefJezek** [stereobooster/beoe#3]
Please add support for hybrid output in Starlight.

my config

```js
markdown: {
      rehypePlugins: [
        [
          rehypeMermaid,
          { class: "not-content", strategy: "img-class-dark-mode", cache },
        ],
      ],
    },
```

```
4:10:11 PM [vite] Error when evaluating SSR module /home/josef/projects/test/astro.config.mjs:
|- RangeError: Maximum call stack size exceeded
    at Function.isArray (<anonymous>)
    at clone (/home/josef/projects/starweb-sites/node_modules/.pnpm/merge@2.1.1/node_modules/merge/lib/src/index.js:34:15)
    at clone (/home/josef/projects/starweb-sites/node_modules/.pnpm/merge@2.1.1/node_modules/merge/lib/src/index.js:43:29)
    at clone (/home/josef/projects/starweb-sites/node_modules/.pnpm/merge@2.1.1/node_modules/merge/lib/src/index.js:43:29)
    at clone (/home/josef/projects/starweb-sites/node_modules/.pnpm/merge@2.1.1/node_modules/merge/lib/src/index.js:43:29)
    at clone (/home/josef/projects/starweb-sites/node_modules/.pnpm/merge@2.1.1/node_modules/merge/lib/src/index.js:43:29)
    at clone (/home/josef/projects/starweb-sites/node_modules/.pnpm/merge@2.1.1/node_modules/merge/lib/src/index.js:43:29)
    at clone (/home/josef/projects/starweb-sites/node_modules/.pnpm/merge@2.1.1/node_modules/merge/lib/src/index.js:43:29)
    at clone (/home/josef/projects/starweb-sites/node_modules/.pnpm/merge@2.1.1/node_modules/merge/lib/src/index.js:43:29)
    at clone (/home/josef/projects/starweb-sites/node_modules/.pnpm/merge@2.1.1/node_modules/merge/lib/src/index.js:43:29)
```

**Comment by stereobooster** [comment]
To be fair I have never used hybrid output. Do you have an example repo?
